Repository redis/redis-doc, pull requests merged in 2019-10, with the labels that each got.

#871 Added note about deprecation
  commands.json
  commands/hmset.md
  commands/hset.md
Labels: waiting-to-hear-back

#965 Update modules.json
  modules.json
Labels: needs-rebase

#948 Updated modules license and added smartcache
  modules.json
Labels: waiting-to-hear-back

#931 Documents the MODULE command(s)
  commands.json
  commands/module-list.md
  commands/module-load.md
  commands/module-unload.md
Labels: needs-review

#853 Add predixy in tools.json
  tools.json
Labels: needs-rebase

#858 add redis-cluster in clients.json
  clients.json
Labels: needs-rebase

#866 Update clients.json
  clients.json
Labels: needs-rebase

#867 Added Noderis client
  clients.json
Labels: needs-rebase

#803 Adds note about conversion of associative arrays
  commands/eval.md
Labels: waiting-to-hear-back

#1178 update lqrm author
  modules.json
Labels: waiting-to-hear-back

#1193 Add a redis web tool for flask user
  tools.json
Labels: waiting-to-hear-back

#605 PFMERGE includes target HLL in the merge
  commands/pfmerge.md
Labels: waiting-for-upstream, waiting-to-hear-back
