Repository redis/redis-doc, pull requests merged in 2021-09, with the labels that each got.

#1637 Clarify what pubsub numpat behavior change
  commands/pubsub.md
Labels: to-be-merged

#1636 Add new LMPOP and BLMPOP commands.
  commands.json
  commands/blmpop.md
  commands/lmpop.md
Labels: waiting-for-upstream

#1136 Formatted ruby examples
  topics/memory-optimization.md
  topics/pipelining.md
Labels: waiting-to-hear-back

#1024 Fix grammar in pipelining doc for easier consumption
  topics/pipelining.md
Labels: waiting-to-hear-back
