Repository redis/redis-doc, pull requests merged in 2021-06, with the labels that each got.

#1585 slowlog get command supports passing in -1 to get all logs.
  commands/slowlog.md
Labels: to-be-merged

#1582 API documentation of EXPIRETIME and PEXPIRETIME commands
  commands.json
  commands/expiretime.md
  commands/pexpiretime.md
Labels: to-be-merged

#1560 EVAL_RO and EVALSHA_RO documentation
  commands.json
  commands/eval_ro.md
  commands/evalsha_ro.md
Labels: to-be-merged

#1579 Add missing flag nofailover in "cluster nodes" command output.
  commands/cluster-nodes.md
Labels: to-be-merged

#1572 MEMORY USAGE command may return 'nil'
  commands/memory-usage.md
Labels: to-be-merged

#1126 Document optionality of PFADD, EVAL, EVALSHA args
  commands.json
Labels: needs-review, to-be-merged

#1565 Update SET documentation for NX and GET
  commands/set.md
Labels: to-be-merged

#1407 Added SWI-Prolog client
  clients.json
Labels: to-be-merged

#1567 Removed wrong space
  topics/cluster-tutorial.md
Labels: formatting, to-be-merged

#1568 GEOSEARCH command: Changed wording in a few places.
  commands/geosearch.md
Labels: to-be-merged

#1569 Rephrase description of XX and NX options of ZADD
  commands/zadd.md
Labels: to-be-merged

#1570 Add note re TTL getting reset by getset
  commands/getset.md
Labels: to-be-merged

#1571 Use 'nil' in LPOS command docs
  commands/lpos.md
Labels: to-be-merged

#1584 Add `Jedis.jl` to clients.json as a new Julia client
  clients.json
Labels: to-be-merged

#1586 Adding ecredis - Erlang Redis Cluster client.
  clients.json
Labels: to-be-merged

#1587 Add redis-interval-module
  modules.json
Labels: to-be-merged

#1581 Added redis-client (Bash): https://github.com/SomajitDey/redis-client
  clients.json
Labels: to-be-merged

#1588 Cleanup erlang clients that are not maintained
  clients.json
Labels: to-be-merged

#1591 Fix the return value description of LPOP and RPOP.
  commands/lpop.md
  commands/rpop.md
Labels: to-be-merged

#612 Update time complexity of EXISTS, LPUSH, RPUSH, SPOP
  commands.json
Labels: to-be-merged

#1457 Update the doc about maxmemory on replicas
  topics/replication.md
Labels: to-be-merged

#1437 Kicked off performance analysis guide - on CPU profilling and tracing
  topics/performance-on-cpu.md
Labels: needs-clarity-review, needs-technical-review
