Repository redis/redis-doc, pull requests merged in 2021-12, with the labels that each got.

#1695 Documents the <ms>-* form for XADD
  commands/xadd.md
  topics/streams-intro.md
Labels: waiting-for-upstream

#1703 Add evicted_clients field in INFO
  commands/info.md
Labels: to-be-merged

#1707 Add current_cow_size_age field in INFO command
  commands/info.md
Labels: to-be-merged

#1709 Add slave_read_repl_offset field to INFO command
  commands/info.md
Labels: to-be-merged

#1713 Add replica_announced field to INFO command
  commands/info.md
Labels: to-be-merged

#1705 muliparameter config get
  commands.json
  commands/config-get.md
Labels: waiting-for-upstream, to-be-merged

#1710 Add API documentation for CLUSTER LINKS command
  commands.json
  commands/cluster-info.md
  commands/cluster-links.md
  commands/info.md
Labels: waiting-for-upstream

#1718 extra spaces correction in sadd example
  topics/data-types-intro.md
Labels: to-be-merged

#1720 io_threads_active field should belong to server instead of clients
  commands/info.md
Labels: to-be-merged

#1726 Readme cleanup
  README.md
Labels: to-be-merged
