Repository redis/redis-doc, pull requests merged in 2021-08, with the labels that each got.

#1610 adds new SINTERCARD and ZINTERCARD
  commands.json
  commands/sintercard.md
  commands/zintercard.md
Labels: waiting-for-upstream

#1613 Add doc for new options of expire commands
  commands.json
  commands/expire.md
  commands/expireat.md
  commands/pexpire.md
  commands/pexpireat.md
Labels: to-be-merged, waiting-for-upstream

#1617 Add current_cow_peak field in INFO command
  commands/info.md
Labels: waiting-for-upstream

#1622 Avoid confusing use of term "pure function"
  commands/eval.md
  wordlist
Labels: to-be-merged

#1621 Add SORT_RO documentation
  commands.json
  commands/georadius.md
  commands/sort.md
  commands/sort_ro.md
Labels: to-be-merged
