Repository redis/redis-doc, pull requests merged in 2022-02, with the labels that each got.

#1765 Replace outdated args with ARGV variable
  commands/eval.md
Labels: to-be-merged

#1766 Typo fix
  topics/functions-intro.md
Labels: to-be-merged

#1759 Add missing newline after reply
  commands/expiretime.md
  commands/pexpiretime.md
Labels: to-be-merged

#1758 Fix wrong server_time_usec INFO field name
  commands/info.md
Labels: to-be-merged

#1769 Add note about acl-pubsub-default default behaviour.
  topics/acl.md
Labels: to-be-merged

#1770 Migrated several documents to new structure
  docs/manual/keyspace-notifications.md
  docs/manual/optimization/benchmarks.md
Labels: new-structure

#1771 Remove extra )
  topics/functions-intro.md
Labels: to-be-merged

#1773 Document how to check if a module API function exists
  topics/modules-intro.md
Labels: to-be-merged

#1760 fix multipart aof backup doc
  commands/info.md
  topics/persistence.md
Labels: waiting-for-upstream

#1777 Added `redis.acl_check_cmd()` documentation.
  topics/lua-api.md
Labels: to-be-merged

#1780 Now summary and since not always present in COMMAND DOCS
  commands/command-docs.md
Labels: to-be-merged

#1779 Fix error hyperlink in function-load
  commands/function-load.md
Labels: to-be-merged

#1782 Merge the two lists of fields (always present and sometimes present)
  commands/command-docs.md
Labels: to-be-merged

#1789 Use `` to generate the hyperlinks for commands
  commands/lmpop.md
Labels: to-be-merged

#1785 Adjust X[AUTO]CLAIM handling deleted entries
  commands/xautoclaim.md
  commands/xclaim.md
Labels: to-be-merged

#1787 Fix incorrect references to SYNC command in function dump doc
  commands/function-flush.md
Labels: to-be-merged

#1796 Fix typo in cluster-tutorial
  topics/cluster-tutorial.md
Labels: to-be-merged

#1794 multipart aof backup details without script
  topics/persistence.md
Labels: waiting-for-upstream

#1793 Fix incorrect link to Sharded Pubsub in SPUBLISH
  commands/spublish.md
  commands/ssubscribe.md
  commands/sunsubscribe.md
Labels: to-be-merged

#1799 Updated documentation for not key
  topics/key-specs.md
Labels: to-be-merged

#1694 Documents consumer group lag
  commands.json
  commands/xgroup-create.md
  commands/xgroup-setid.md
  commands/xinfo-groups.md
  commands/xinfo-stream.md
  topics/streams-intro.md
Labels: to-be-merged

#1791 fix typo in eval-intro
  topics/eval-intro.md
Labels: to-be-merged
