Repository redis/redis-doc, pull requests merged in 2022-01, with the labels that each got.

#1711 Update SHUTDOWN and Signal Handling
  commands.json
  commands/info.md
  commands/shutdown.md
  topics/signals.md
Labels: waiting-for-upstream

#1729 Fix client_recent_max_input_buffer/client_recent_max_output_buffer fi…
  commands/info.md
Labels: to-be-merged

#1724 Add multi part aof information
  topics/persistence.md
Labels: waiting-for-upstream, to-be-merged

#1731 Add lazyfreed_objects field in INFO
  commands/info.md
Labels: to-be-merged

#1732 Add dump_payload_sanitizations field in INFO
  commands/info.md
Labels: to-be-merged

#1737 Use " instead of ` for better readability in protocol.md
  topics/protocol.md
Labels: to-be-merged

#1715 Added clusterhostnames and define unknown endpoints
  commands/cluster-slots.md
  topics/cluster-spec.md
  wordlist
Labels: waiting-for-upstream

#1685 Added redli to list of clients
  tools.json
Labels: to-be-merged

#1740 Add multi-mem and resp in CLIENT LIST
  commands/client-list.md
Labels: to-be-merged

#1697 Refresh COMMAND, add topics: command-args, key-specs
  commands.json
  commands/command-docs.md
  commands/command-list.md
  commands/command.md
  topics/command-arguments.md
  topics/command-tips.md
  topics/key-specs.md
  wordlist
Labels: to-be-merged

#1733 Updated docs to include INFO latencystats and LATENCY HISTOGRAM
  README.md
  commands/info.md
  commands/latency-histogram.md
  wordlist
Labels: to-be-merged

#1750 Fix shutdown_in_milliseconds wrong name in INFO
  commands/info.md
Labels: to-be-merged

#1717 Add documentation for pubsub shard.
  commands/pubsub-shardchannels.md
  commands/pubsub-shardnumsub.md
  commands/spublish.md
  commands/ssubscribe.md
  commands/subscribe.md
  commands/sunsubscribe.md
  topics/cluster-spec.md
  topics/pubsub.md
Labels: to-be-merged

#1756 Documentation for ACL V2 + ACL DRYRUN
  commands/acl-dryrun.md
  commands/acl-getuser.md
  commands/acl-setuser.md
  topics/acl.md
Labels: to-be-merged

#1761 doc improvements around acl sub-commands and key-spec notes
  commands/acl-setuser.md
  topics/acl.md
  topics/key-specs.md
Labels: to-be-merged

#1757 Added comment that `aof_rewrite_buffer_length` was removed in 7.0
  commands/info.md
  commands/memory-stats.md
Labels: to-be-merged

#1725 Redis Programmability Documentation
  commands/eval.md
  commands/eval_ro.md
  commands/evalsha.md
  commands/evalsha_ro.md
  commands/fcall.md
  commands/fcall_ro.md
  commands/function-create.md
  commands/function-delete.md
  commands/function-dump.md
  commands/function-flush.md
  commands/function-info.md
  commands/function-kill.md
  commands/function-list.md
  commands/function-load.md
  commands/function-restore.md
  commands/function-stats.md
  commands/script-debug.md
  commands/script-exists.md
  commands/script-flush.md
  commands/script-kill.md
  commands/script-load.md
  topics/eval-intro.md
  topics/functions-intro.md
  topics/ldb.md
  topics/lua-api.md
  topics/programmability.md
  wordlist
Labels: to-be-merged

#1755 Updates docs for CLI, FAQ, and QuickStart
  docs/ARM.md
  docs/getting-started/faq.md
  docs/getting-started/quickstart.md
  docs/manual/cli.md
  docs/manual/config.md
  docs/reference/ARM.md
Labels: new-structure

#1754 Updates docs for governance, clients and distributed locks
  docs/clients.md
  docs/project/governance.md
  docs/reference/patterns/distributed-locks.md
Labels: new-structure

#1753 Reorg and copyedits: acl, security, signals, protocol, latency-monitor
  docs/latency-monitor.md
  docs/manual/acl.md
  docs/manual/optimization/latency-monitor.md
  docs/manual/security.md
  docs/protocol.md
  docs/reference/protocol-spec.md
  docs/reference/signals.md
  docs/signals.md
Labels: new-structure

#1751 New structure for: admin, ldb, pubsub, memory-optimization, transaction, pipelining
  docs/manual/admin.md
  docs/manual/lua-debugging.md
  docs/manual/pipelining.md
  docs/manual/pubsub.md
  docs/manual/reference/memory-optimization.md
  docs/manual/transactions.md
  docs/pipelining.md
Labels: new-structure
